name: Docker Image CI

on:
  push:
    branches: ['master']
  pull_request:
    branches: ['master']

jobs:
  build:
    runs-on: ubuntu-latest
    env: 
      DOCKER_USER: ${{ secrets.DOCKER_USER }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Login on docker HUB
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          echo "Login starts"
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
          echo "Login ended"
      - name: Building the docker image
        run: |
          echo $DOCKER_USER 
          docker build . --file Dockerfile --tag $DOCKER_USER/docker-actions:0.0.2
      - name: Pushing Docker Image
        run: |
          docker push $DOCKER_USER/docker-actions:0.0.2

      # - name: Build the Docker image
      #   run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
